spring:
  h2:
    console:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:db
      driver-class-name: org.h2.Driver
      username: sa
      password: password

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto:  none
    generate-ddl: false # Whether to initialize the schema on startup.
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        format_sql: false