-- ⭐ ROUND(수, 반올림 할 자릿수)
-- ⭐ ROUND(수, 버림 할 자릿수)
-- ⭐ DATEDIFF(END_DATE, START_DATE) : 일 차이 가져올 때 활용
-- ⭐ TIMESTAMPDIFF(단위, END_DATE, START_DATE) : 연, 분기, 월, 주, 일, 시, 분, 초 단위를 지정하여 차이를 구할 때 활용

SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)) + 1, 1) AS 'AVERAGE_DURATION'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC