SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS 'FILE_PATH'
FROM USED_GOODS_FILE F
INNER JOIN USED_GOODS_BOARD B
USING(BOARD_ID)
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC