-- ⭐ SUM(A * B) AS 출력이름
-- ⭐ 1번 우선순위 정렬 조건, 2번 우선순위 정렬 조건 (,로 정렬 우선순위 나열)

SELECT PRODUCT_CODE, SUM(A.PRICE * B.SALES_AMOUNT) AS SALES
FROM PRODUCT A
INNER JOIN OFFLINE_SALE B
USING(PRODUCT_ID)
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE