-- ⭐ SUM(A * B) AS 출력이름
-- ⭐ 1번 우선순위 정렬 조건, 2번 우선순위 정렬 조건 (,로 정렬 우선순위 나열)

SELECT P.PRODUCT_CODE, SUM(P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM PRODUCT P
INNER JOIN OFFLINE_SALE OS
ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC