-- ⭐ LEFT OUTER JOIN에서 왼쪽 테이블에만 있는 것을 표현할 때 IS NULL 활용

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT OUTER JOIN ANIMAL_INS I
USING(ANIMAL_ID)
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID, O.NAME