-- ⭐ (일반 서브 쿼리) 단건 조회를 통한 조건절 완성

SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW A
INNER JOIN MEMBER_PROFILE B
USING (MEMBER_ID)
WHERE MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
)
ORDER BY A.REVIEW_DATE, A.REVIEW_TEXT

-- ⭐ NATURAL JOIN : 조인 대상이 되는 두 테이블의 컬럼명이 동일한 경우 사용

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE A
NATURAL JOIN REST_REVIEW B
WHERE MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
    )
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT