SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
INNER JOIN MEMBER_PROFILE M
USING (MEMBER_ID)
WHERE MEMBER_ID =
      (
      SELECT MEMBER_ID
      FROM REST_REVIEW
      GROUP BY MEMBER_ID
      ORDER BY COUNT(*) DESC
      LIMIT 1
      )
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT