-- ⭐ DATE_FORMAT %h 시간 (12시간)
-- ⭐ DATE_FORMAT %H 시간 (24시간)
-- ⭐ DATE_FORMAT %i 분
-- ⭐ 출력 되는 컬럼 명 기준으로 조건 지정 가능

SELECT DATE_FORMAT(DATETIME, '%H:%i') AS 'HOUR', COUNT(ANIMAL_ID) AS 'COUNT'
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY HOUR