SELECT MCDP_CD AS '진료과 코드', COUNT(*) AS '5월진료예약건수'
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m') = '2022-05'
GROUP BY MCDP_CD
ORDER BY COUNT(*), MCDP_CD

-- ⭐ 정렬 조건 적용 시, 컬럼 순번으로 지정 가능
SELECT MCDP_CD AS '진료과 코드', COUNT(*) AS '5월진료예약건수'
FROM APPOINTMENT
WHERE APNT_YMD LIKE '2022-05%'
GROUP BY MCDP_CD
ORDER BY 2, 1