-- ⭐ GROUP BY + HAVING : GROUP BY 절에서 조건을 주려면 WHERE 대신 HAVING 사용
-- ⭐ IN : 여러 값을 OR 관계로 묶어 나열

SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS 'count'
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
HAVING ANIMAL_TYPE IN ('cat', 'dog')
ORDER BY ANIMAL_TYPE

SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE)
FROM ANIMAL_INS
WHERE REGEXP_LIKE(ANIMAL_TYPE, 'Cat|Dog')
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE