-- ⭐ 서브 쿼리 사용할 때 주의할 점 (1. 괄호 2. ORDER BY 사용 불가능 ...)
-- ⭐ 서브 쿼리 사용 가능한 곳 (1. SELECT, FROM, WHERE, HAVING ...)

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A,
     (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) B
WHERE A.FOOD_TYPE = B.FOOD_TYPE
      AND A.FAVORITES = B.FAVORITES
ORDER BY FOOD_TYPE DESC