WITH RECURSIVE TIME(HOUR) AS (
    SELECT 0
    UNION ALL
    SELECT HOUR + 1 FROM TIME WHERE HOUR < 23
)

SELECT A.HOUR, CASE WHEN B.CNT IS NULL THEN 0 ELSE B.CNT END AS 'COUNT'
FROM TIME A
LEFT JOIN (
    SELECT HOUR(DATETIME) AS 'H', COUNT(ANIMAL_ID) AS 'CNT'
    FROM ANIMAL_OUTS
    GROUP BY H
) AS B
ON A.HOUR = B.H