SELECT
    YEAR(O.SALES_DATE) AS 'YEAR',
    MONTH(O.SALES_DATE) AS 'MONTH',
    GENDER,
    COUNT(DISTINCT USER_ID) AS 'USERS'
FROM USER_INFO U
INNER JOIN ONLINE_SALE O
USING(USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER