-- ⭐ COALESCE : 인자로 주어진 컬럼들 중에서 NULL이 아닌 첫 번째 값을 반환하는 함수

SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID