spring:
  datasource:
    url: jdbc:mysql://mysql:3306/intly
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  #
  flyway:
    url: jdbc:mysql://mysql:3306/intly
    user: root
    password: password
    connectRetries: 10
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/seed
