version: '3'

services:
  backend:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: hanghae
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d

volumes:
  mysql: