-- ⭐ UNION (= UNION DISTINCT) : 중복되는 레코드 제거
-- ⭐ UNION ALL : 중복 제거 X

(
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE, '%m') = '03'
)
UNION ALL
(
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE, '%m') = '03'
)
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID